'use client';
import {useEffect,useState} from 'react';

type Msg={role:'user'|'ai';text:string};
type PendingPolicy={model:string;tokenLimitPerDay:number;requestsPerHour:number;minIntervalSeconds:number;maxCompletionTokens:number;textOnly:boolean};
type Account={status?:'pending'|'approved'|'suspended'|'rejected';pendingChatPolicy?:PendingPolicy};
const routes=[['auto','Auto'],['fast','Fast'],['balanced','Balanced'],['deep','Deep']] as const;

export default function Chat(){
  const [text,setText]=useState('');const [busy,setBusy]=useState(false);const [model,setModel]=useState('auto');const [account,setAccount]=useState<Account|null>(null);
  const [msgs,setMsgs]=useState<Msg[]>([{role:'ai',text:'สวัสดีครับ ผมคือ Daiki AI วันนี้ให้ช่วยเรื่องอะไร?'}]);
  useEffect(()=>{void fetch('/api/account',{cache:'no-store'}).then(async r=>{if(r.ok){const a=await r.json() as Account;setAccount(a);if(a.status==='pending')setModel('fast')}}).catch(()=>{})},[]);
  const pending=account?.status==='pending';
  const send=async()=>{if(!text.trim()||busy)return;const q=text;const history=[...msgs,{role:'user' as const,text:q}];setMsgs([...history,{role:'ai',text:''}]);setText('');setBusy(true);try{const r=await fetch('/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({model:pending?'fast':model,messages:history.map(m=>({role:m.role==='ai'?'assistant':'user',content:m.text})),stream:true})});if(!r.ok||!r.body){const d=await r.json().catch(()=>({error:'Gateway unavailable'}));const suffix=d.retryAfterSeconds?` ลองใหม่ใน ${d.retryAfterSeconds} วินาที`:'';throw new Error((d.error||'Gateway unavailable')+suffix)}const reader=r.body.getReader();const dec=new TextDecoder();let buf='';let answer='';while(true){const {done,value}=await reader.read();if(done)break;buf+=dec.decode(value,{stream:true});const lines=buf.split('\n');buf=lines.pop()||'';for(const raw of lines){const line=raw.trim();if(!line.startsWith('data:'))continue;const data=line.slice(5).trim();if(!data||data==='[DONE]')continue;try{const j=JSON.parse(data);const chunk=j?.choices?.[0]?.delta?.content||'';if(chunk){answer+=chunk;setMsgs(x=>x.map((m,i)=>i===x.length-1?{...m,text:answer}:m))}}catch{}}}if(!answer)setMsgs(x=>x.map((m,i)=>i===x.length-1?{...m,text:'โมเดลไม่ได้ส่งข้อความกลับมา'}:m))}catch(e){setMsgs(x=>x.map((m,i)=>i===x.length-1?{...m,text:`เชื่อมต่อ AI ไม่สำเร็จ: ${e instanceof Error?e.message:String(e)}`}:m))}finally{setBusy(false)}};
  const p=account?.pendingChatPolicy;
  return <><div className="top"><div><div className="h1">Chat</div><div className="muted">{pending?'Restricted chat while waiting for whitelist approval':'Private workspace ผ่าน Daiki model router'}</div></div><select className="input select" value={pending?'fast':model} disabled={pending} onChange={e=>setModel(e.target.value)}>{(pending?[['fast','Fast'] as const]:routes).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></div>{pending&&p&&<section className="card pendingNotice"><strong>Pending access</strong><div className="muted small">Chat only · Fast route · {p.tokenLimitPerDay.toLocaleString()} tokens/day · {p.requestsPerHour} messages/hour · {p.minIntervalSeconds}s cooldown · max {p.maxCompletionTokens} output tokens</div></section>}<div className="chat" style={{marginTop:pending?16:0}}><section className="card conversation"><div className="messages">{msgs.map((m,i)=><div key={i} className={`bubble ${m.role}`}>{m.text||<span className="muted">กำลังตอบ…</span>}</div>)}</div><div className="composer"><textarea className="input" rows={2} value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send()}}} placeholder="ถามอะไรก็ได้..."/><button className="btn primary" disabled={busy} onClick={()=>void send()}>{busy?'Queued / Generating…':'Send'}</button></div></section><aside className="card"><b>Session</b><p className="muted">Model alias</p><p>{pending?'fast':model}</p><p className="muted">Access</p><span className="pill"><span className="dot"/>{pending?'Restricted':'Approved'}</span><hr/><p className="muted">Privacy</p><p>Browser → Daiki Backend → controlled queue → LiteLLM. Physical model names and upstream credentials remain server-side.</p></aside></div></>;
}
