'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';

type Policy={quotaMode:'unlimited'|'limited';tokenLimit?:number;intervalKind:'hour'|'day'|'week'|'month'|'rolling'|'custom'|'lifetime';intervalSeconds?:number;allowedModels?:string[]|string};
type UsageRow={subject:string;email?:string;displayName?:string;status:string;totalTokens:number;requests:number};
const DEFAULT:Policy={quotaMode:'unlimited',intervalKind:'month'};
const windows:Policy['intervalKind'][]=['hour','day','week','month','rolling','custom','lifetime'];

export function AdminTokens(){
  const [policy,setPolicy]=useState<Policy>(DEFAULT);const [rows,setRows]=useState<UsageRow[]>([]);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
  const load=useCallback(async()=>{const [p,u]=await Promise.all([fetch('/api/admin/token-policy',{cache:'no-store'}),fetch('/api/admin/usage',{cache:'no-store'})]);if(p.ok){const d=await p.json();setPolicy({...DEFAULT,...(d.policy||{})})}if(u.ok)setRows(await u.json())},[]);
  useEffect(()=>{const t=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(t)},[load]);
  const total=useMemo(()=>rows.reduce((n,r)=>n+(r.totalTokens||0),0),[rows]);
  const save=async()=>{setBusy(true);setMessage('');const payload={...policy,tokenLimit:policy.quotaMode==='limited'?Number(policy.tokenLimit||0):undefined,intervalSeconds:['rolling','custom'].includes(policy.intervalKind)?Number(policy.intervalSeconds||3600):undefined,allowedModels:['auto','fast','balanced','deep']};const r=await fetch('/api/admin/token-policy',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));setMessage(r.ok?'System token policy saved.':d.error||'Unable to save policy');if(r.ok)await load();setBusy(false)};
  return <><header className="pageHeader"><div><div className="eyebrow">Entitlements</div><h1>Token Settings</h1><p>Set the default token allowance inherited by users and API keys unless a more specific override exists.</p></div><button className="btn primary" disabled={busy} onClick={()=>void save()}>{busy?'Saving…':'Save policy'}</button></header>
  <div className="pastelGrid"><div className="pastelCard peach"><span>System mode</span><strong>{policy.quotaMode}</strong><small>default entitlement</small></div><div className="pastelCard sky"><span>Window</span><strong>{policy.intervalKind}</strong><small>reset interval</small></div><div className="pastelCard mint"><span>Total usage</span><strong>{new Intl.NumberFormat().format(total)}</strong><small>completed tokens</small></div></div>
  <section className="surface sectionGap"><div className="sectionHead"><div><h2>Default policy</h2><p className="muted small">User/API-key overrides take precedence over this system default.</p></div></div><div className="formGrid sectionGap"><label><span>Quota mode</span><select className="input" value={policy.quotaMode} onChange={e=>setPolicy(x=>({...x,quotaMode:e.target.value as Policy['quotaMode']}))}><option value="unlimited">Unlimited</option><option value="limited">Limited</option></select></label><label><span>Interval</span><select className="input" value={policy.intervalKind} onChange={e=>setPolicy(x=>({...x,intervalKind:e.target.value as Policy['intervalKind']}))}>{windows.map(x=><option key={x}>{x}</option>)}</select></label>{policy.quotaMode==='limited'?<label><span>Token limit</span><input className="input" type="number" min="0" value={policy.tokenLimit??1000000} onChange={e=>setPolicy(x=>({...x,tokenLimit:Number(e.target.value)}))}/></label>:null}{['rolling','custom'].includes(policy.intervalKind)?<label><span>Interval seconds</span><input className="input" type="number" min="1" value={policy.intervalSeconds??3600} onChange={e=>setPolicy(x=>({...x,intervalSeconds:Number(e.target.value)}))}/></label>:null}</div>{message?<div className="notice butter sectionGap">{message}</div>:null}</section>
  <section className="surface tableSurface sectionGap"><div className="sectionHead"><h2>Usage overview</h2><span className="muted small">Per-user overrides remain configurable from Users</span></div><div className="tableWrap"><table className="table"><thead><tr><th>User</th><th>Status</th><th>Requests</th><th>Total tokens</th></tr></thead><tbody>{rows.map(r=><tr key={r.subject}><td><strong>{r.displayName||r.email||r.subject}</strong><div className="muted small">{r.email||r.subject}</div></td><td><span className={`status status-${r.status}`}>{r.status}</span></td><td>{r.requests}</td><td><strong>{new Intl.NumberFormat().format(r.totalTokens||0)}</strong></td></tr>)}</tbody></table></div></section></>;
}
