'use client';
import Link from 'next/link';
import {useCallback,useEffect,useMemo,useState} from 'react';
type Device={guestSubject:string;deviceId:string;deviceName?:string;requests:number;inputTokens:number;outputTokens:number;totalTokens:number;lastSeenAt:string;lastUsedAt?:string};
type PolicyResponse={devices?:Device[];usage?:{totalTokens?:number};requests?:number};
type Group={guestSubject:string;devices:Device[];requests:number;tokens:number;lastSeenAt:string};
const fmt=(n:number)=>new Intl.NumberFormat().format(n||0);const short=(v:string)=>v.startsWith('guest:')?`guest:${v.slice(6,14)}…`:v;const when=(v:string)=>new Date(v).toLocaleString();
export function AdminGuests(){
 const [devices,setDevices]=useState<Device[]>([]);const [requests,setRequests]=useState(0);const [tokens,setTokens]=useState(0);const [query,setQuery]=useState('');const [loading,setLoading]=useState(true);const [message,setMessage]=useState('');const [resetting,setResetting]=useState('');
 const load=useCallback(async()=>{setLoading(true);const r=await fetch('/api/admin/guest-policy',{cache:'no-store'});if(r.ok){const d=await r.json() as PolicyResponse;setDevices(Array.isArray(d.devices)?d.devices:[]);setRequests(Number(d.requests||0));setTokens(Number(d.usage?.totalTokens||0))}setLoading(false)},[]);
 useEffect(()=>{const t=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(t)},[load]);
 const groups=useMemo(()=>{const m=new Map<string,Group>();for(const d of devices){const g=m.get(d.guestSubject)||{guestSubject:d.guestSubject,devices:[],requests:0,tokens:0,lastSeenAt:d.lastSeenAt};g.devices.push(d);g.requests+=Number(d.requests||0);g.tokens+=Number(d.totalTokens||0);if(new Date(d.lastSeenAt)>new Date(g.lastSeenAt))g.lastSeenAt=d.lastSeenAt;m.set(d.guestSubject,g)}return [...m.values()].sort((a,b)=>+new Date(b.lastSeenAt)-+new Date(a.lastSeenAt))},[devices]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return groups;return groups.filter(g=>g.guestSubject.toLowerCase().includes(q)||g.devices.some(d=>(d.deviceName||'').toLowerCase().includes(q)||d.deviceId.toLowerCase().includes(q)))},[groups,query]);
 const reset=async(subject:string)=>{setResetting(subject);setMessage('');const r=await fetch(`/api/admin/guests/${encodeURIComponent(subject)}/quota-reset`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({note:'Reset from Guest Management'})});const d=await r.json().catch(()=>({})) as {error?:string};setMessage(r.ok?`Reset ${short(subject)} แล้ว`:d.error||'Reset ไม่สำเร็จ');if(r.ok)await load();setResetting('')};
 return <><header className="pageHeader"><div><div className="eyebrow">Guest intelligence</div><h1>Guest Management</h1><p>ดู Guest แบบรวมตาม network identity แล้วกดเข้าไปดู conversation, activity, model, token และไฟล์ของแต่ละ device ได้</p></div><div className="actions"><Link className="btn ghost" href="/admin/tokens">Guest policy</Link><button className="btn" onClick={()=>void load()}>Refresh</button></div></header>
 <div className="pastelGrid"><div className="pastelCard peach"><span>Networks</span><strong>{fmt(groups.length)}</strong><small>hashed identities</small></div><div className="pastelCard sky"><span>Devices</span><strong>{fmt(devices.length)}</strong><small>browser/device identities</small></div><div className="pastelCard mint"><span>Requests</span><strong>{fmt(requests)}</strong><small>completed Guest requests</small></div><div className="pastelCard butter"><span>Tokens</span><strong>{fmt(tokens)}</strong><small>Guest lifetime usage</small></div></div>
 <section className="surface sectionGap guestDirectory"><div className="sectionHead"><div><h2>Guest identities</h2><p className="muted small">ไม่แสดง raw IP; network ID เป็น one-way hash และ device ID ใช้เพื่อแยก session/cooldown</p></div><input className="input guestSearch" value={query} onChange={e=>setQuery(e.target.value)} placeholder="ค้นหา network, device name หรือ device ID"/></div>{message?<div className="notice butter sectionGap">{message}</div>:null}
 <div className="guestNetworkList sectionGap">{loading?<div className="emptyState">Loading guests…</div>:filtered.length?filtered.map(g=><article className="guestNetworkCard" key={g.guestSubject}><div className="guestNetworkMain"><div><div className="guestIdentityLine"><strong>{short(g.guestSubject)}</strong><code>{g.guestSubject}</code></div><div className="guestDeviceChips">{g.devices.slice(0,6).map(d=><span key={d.deviceId}>{d.deviceName||'Unnamed'} <small>{d.deviceId.slice(0,10)}{d.deviceId.length>10?'…':''}</small></span>)}{g.devices.length>6?<span>+{g.devices.length-6} devices</span>:null}</div></div><div className="guestNetworkStats"><span><b>{fmt(g.requests)}</b><small>requests</small></span><span><b>{fmt(g.tokens)}</b><small>tokens</small></span><span><b>{g.devices.length}</b><small>devices</small></span><span><b>{when(g.lastSeenAt)}</b><small>last seen</small></span></div></div><div className="guestNetworkActions"><button className="btn compact ghost" disabled={resetting===g.guestSubject} onClick={()=>void reset(g.guestSubject)}>{resetting===g.guestSubject?'Resetting…':'Reset quota'}</button><Link className="btn compact primary" href={`/admin/guests/${g.guestSubject}`}>View activity</Link></div></article>):<div className="emptyState">ไม่พบ Guest ที่ตรงกับการค้นหา</div>}</div></section></>;
}
