'use client';
import Link from 'next/link';
import {useCallback,useEffect,useMemo,useState} from 'react';

type Period='day'|'month'|'year';
type User={subject:string;displayName?:string;email?:string;status:string;authProvider?:string;roles?:string[];lastLoginAt?:string;createdAt?:string};
type APIKey={id:string;name:string;keyPrefix:string;scopes:string[];status:string;createdAt:string;expiresAt?:string;lastUsedAt?:string};
type Connection={provider:string;email:string;scopes:string[];connectedAt:string;updatedAt:string};
type Capability={kind:string;name:string;requests:number;totalTokens:number;lastUsedAt?:string};
type Bucket={label:string;inputTokens:number;outputTokens:number;totalTokens:number;requests:number};
type Activity={requestId:string;apiKeyId?:string;modelAlias:string;workload:string;inputTokens:number;outputTokens:number;totalTokens:number;status:string;metadata:Record<string,unknown>;startedAt:string;completedAt?:string};
type UsageRange={tokens:{inputTokens:number;outputTokens:number;totalTokens:number};requests:number};
type Detail={user:User;apiKeys:APIKey[];apiKeySummary:{total:number;active:number;revoked:number};connections:Connection[];capabilities:Capability[];quota:{policy:Record<string,unknown>;configured:boolean};usage:{day:UsageRange;month:UsageRange;year:UsageRange;lifetime:UsageRange;period:Period;series:Bucket[]};activity:Activity[];dataPolicy:Record<string,unknown>};
const fmt=(n:number)=>new Intl.NumberFormat().format(n||0);
const when=(v?:string)=>v?new Date(v).toLocaleString():'—';

export function AdminUserDetail({subject}:{subject:string}){
 const [period,setPeriod]=useState<Period>('month');const [data,setData]=useState<Detail|null>(null);const [busy,setBusy]=useState('');const [message,setMessage]=useState('');const [keyName,setKeyName]=useState('developer-key');const [keyExpiry,setKeyExpiry]=useState('');const [secret,setSecret]=useState('');
 const load=useCallback(async(p:Period)=>{const r=await fetch(`/api/admin/users/${encodeURIComponent(subject)}?period=${p}`,{cache:'no-store'});if(r.ok)setData(await r.json())},[subject]);
 useEffect(()=>{const t=window.setTimeout(()=>void load(period),0);return()=>window.clearTimeout(t)},[load,period]);
 const maxTokens=useMemo(()=>Math.max(1,...(data?.usage.series||[]).map(x=>x.totalTokens)),[data]);
 const createKey=async()=>{if(!data)return;setBusy('create-key');setSecret('');setMessage('');const r=await fetch('/api/admin/keys',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:keyName.trim()||'developer-key',ownerSubject:data.user.subject,scopes:['inference'],expiresAt:keyExpiry?new Date(keyExpiry).toISOString():undefined})});const d=await r.json().catch(()=>({}));if(r.ok){setSecret(d.key||'');setMessage('API key created. Copy it now; the secret is shown once.');await load(period)}else setMessage(d.error||'Unable to create API key');setBusy('')};
 const revoke=async(k:APIKey)=>{if(!confirm(`Revoke ${k.name}?`))return;setBusy(k.id);const r=await fetch(`/api/admin/keys/${encodeURIComponent(k.id)}`,{method:'DELETE'});if(r.ok)await load(period);setBusy('')};
 if(!data)return <div className="surface"><div className="emptyState">Loading user detail…</div></div>;
 const u=data.user;const ranges=[['24 hours',data.usage.day],['30 days',data.usage.month],['12 months',data.usage.year],['Lifetime',data.usage.lifetime]] as const;
 const groups=['tool','skill','mcp','connector'].map(kind=>({kind,items:data.capabilities.filter(x=>x.kind===kind)}));
 return <>
  <header className="pageHeader"><div><div className="eyebrow">User Intelligence</div><h1>{u.displayName||u.email||'User'}</h1><p>{u.email||u.subject} · {u.authProvider||'keycloak'} · <span className={`status status-${u.status}`}>{u.status}</span></p></div><div className="actions"><Link className="btn ghost" href="/admin/users">Back to users</Link><Link className="btn" href="/admin/api-keys">API Key Management</Link></div></header>
  <section className="pastelGrid"><article className="pastelCard peach"><span>API keys</span><strong>{data.apiKeySummary.active}</strong><small>{data.apiKeySummary.total} total · {data.apiKeySummary.revoked} revoked</small></article><article className="pastelCard sky"><span>Tokens · 30 days</span><strong>{fmt(data.usage.month.tokens.totalTokens)}</strong><small>{fmt(data.usage.month.requests)} requests</small></article><article className="pastelCard mint"><span>Connections</span><strong>{data.connections.length}</strong><small>OAuth / external services</small></article><article className="pastelCard blush"><span>Capabilities used</span><strong>{data.capabilities.length}</strong><small>Tools · Skills · MCP · Connectors</small></article></section>
  <section className="adminGrid">
   <article className="surface"><div className="sectionHead"><div><h2>Account & access</h2><p className="muted small">Identity, roles, lifecycle and quota inheritance.</p></div></div><div className="detailFacts sectionGap"><div><span>Subject</span><code>{u.subject}</code></div><div><span>Roles</span><strong>{(u.roles||[]).join(', ')||'—'}</strong></div><div><span>Created</span><strong>{when(u.createdAt)}</strong></div><div><span>Last login</span><strong>{when(u.lastLoginAt)}</strong></div><div><span>Quota source</span><strong>{data.quota.configured?'User override':'Inherited'}</strong></div><div><span>Quota policy</span><code>{JSON.stringify(data.quota.policy)}</code></div></div></article>
   <article className="surface"><div className="sectionHead"><div><h2>Data captured</h2><p className="muted small">Operational history is retained without exposing credential secrets.</p></div></div><div className="detailFacts sectionGap"><div><span>Request / response snapshots</span><strong>Enabled</strong></div><div><span>Snapshot limit</span><strong>{fmt(Number(data.dataPolicy.snapshotLimitBytes||0))} bytes</strong></div><div><span>Credential fields</span><strong>Redacted</strong></div><div><span>Raw API keys</span><strong>Never stored</strong></div><div><span>OAuth refresh tokens</span><strong>Encrypted / not exposed</strong></div></div></article>
  </section>
  <section className="surface sectionGap"><div className="sectionHead"><div><h2>Token usage</h2><p className="muted small">Input/output/total token usage and request volume.</p></div><div className="actions">{(['day','month','year'] as Period[]).map(p=><button key={p} className={`btn compact ${period===p?'primary':'ghost'}`} onClick={()=>setPeriod(p)}>{p}</button>)}</div></div><div className="usageRangeGrid sectionGap">{ranges.map(([label,x])=><div className="usageRange" key={label}><span>{label}</span><strong>{fmt(x.tokens.totalTokens)}</strong><small>{fmt(x.tokens.inputTokens)} in · {fmt(x.tokens.outputTokens)} out · {fmt(x.requests)} requests</small></div>)}</div><div className="usageBars sectionGap">{data.usage.series.length?data.usage.series.map(x=><div className="usageBarRow" key={x.label}><span>{x.label}</span><div className="usageBarTrack"><i style={{width:`${Math.max(2,(x.totalTokens/maxTokens)*100)}%`}}/></div><strong>{fmt(x.totalTokens)}</strong><small>{x.requests} req</small></div>):<div className="emptyState">No completed usage in this period.</div>}</div></section>
  <section className="surface sectionGap"><div className="sectionHead"><div><h2>API keys</h2><p className="muted small">Create, inspect and revoke keys owned by this user.</p></div><span className="muted small">{data.apiKeySummary.active} active</span></div><div className="formGrid sectionGap"><label><span>Key name</span><input className="input" value={keyName} onChange={e=>setKeyName(e.target.value)}/></label><label><span>Expiry (optional)</span><input className="input" type="datetime-local" value={keyExpiry} onChange={e=>setKeyExpiry(e.target.value)}/></label></div><div className="actions sectionGap"><button className="btn primary" disabled={busy==='create-key'} onClick={()=>void createKey()}>{busy==='create-key'?'Creating…':'Generate API key'}</button></div>{secret?<div className="secretBox sectionGap"><span>Secret · shown once</span><code>{secret}</code><button className="btn compact" onClick={()=>navigator.clipboard.writeText(secret)}>Copy</button></div>:null}{message?<div className="notice butter sectionGap">{message}</div>:null}<div className="tableWrap sectionGap"><table className="table"><thead><tr><th>Name</th><th>Prefix</th><th>Status</th><th>Scopes</th><th>Last used</th><th>Action</th></tr></thead><tbody>{data.apiKeys.map(k=><tr key={k.id}><td><strong>{k.name}</strong><div className="muted small">{k.id}</div></td><td><code>{k.keyPrefix}</code></td><td><span className={`status status-${k.status}`}>{k.status}</span></td><td>{k.scopes.join(', ')}</td><td>{when(k.lastUsedAt)}</td><td>{k.status==='active'?<button className="btn compact ghost" disabled={busy===k.id} onClick={()=>void revoke(k)}>Revoke</button>:'—'}</td></tr>)}</tbody></table>{!data.apiKeys.length?<div className="emptyState">No API keys for this user.</div>:null}</div></section>
  <section className="adminGrid"><article className="surface"><div className="sectionHead"><div><h2>Connections</h2><p className="muted small">OAuth and external services connected to this identity.</p></div></div>{data.connections.length?<div className="detailList sectionGap">{data.connections.map(x=><div className="detailListRow" key={`${x.provider}-${x.email}`}><div><strong>{x.provider}</strong><div className="muted small">{x.email}</div></div><div className="small">{x.scopes.join(', ')}</div><span>{when(x.updatedAt)}</span></div>)}</div>:<div className="emptyState">No user-scoped connections recorded.</div>}</article><article className="surface"><div className="sectionHead"><div><h2>Tools, skills & MCP</h2><p className="muted small">Capabilities observed in recorded usage.</p></div></div><div className="capabilityGroups sectionGap">{groups.map(g=><div key={g.kind}><strong className="capabilityTitle">{g.kind}</strong>{g.items.length?g.items.map(x=><div className="capabilityRow" key={`${g.kind}-${x.name}`}><span>{x.name}</span><small>{x.requests} req · {fmt(x.totalTokens)} tokens</small></div>):<div className="muted small">None recorded</div>}</div>)}</div></article></section>
  <section className="surface tableSurface sectionGap"><div className="sectionHead"><div><h2>Activity history</h2><p className="muted small">Latest 100 inference requests including model, key, token and redacted payload metadata.</p></div></div><div className="tableWrap"><table className="table activityTable"><thead><tr><th>Time</th><th>Request</th><th>Model</th><th>Auth</th><th>Tokens</th><th>Status</th><th>Data</th></tr></thead><tbody>{data.activity.map(x=><tr key={x.requestId}><td className="small">{when(x.startedAt)}</td><td><code>{x.requestId}</code></td><td>{x.modelAlias}<div className="muted small">{x.workload}</div></td><td>{x.apiKeyId?'API key':'OIDC'}<div className="muted small">{x.apiKeyId||''}</div></td><td><strong>{fmt(x.totalTokens)}</strong><div className="muted small">{fmt(x.inputTokens)} in · {fmt(x.outputTokens)} out</div></td><td><span className={`status status-${x.status}`}>{x.status}</span></td><td><details><summary>View</summary><pre className="metadataPre">{JSON.stringify(x.metadata,null,2)}</pre></details></td></tr>)}</tbody></table>{!data.activity.length?<div className="emptyState">No activity recorded yet.</div>:null}</div></section>
 </>;
}
