'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {Cpu,Link2,Plus,RefreshCw,ServerCog,Trash2,Zap} from 'lucide-react';

type ProviderType='vllm'|'lmstudio'|'ollama';
type Provider={id:string;name:string;providerType:ProviderType;baseUrl:string;hasApiKey:boolean;enabled:boolean;lastTestStatus:string;lastTestMessage:string;lastTestAt?:string};
type Model={id:string;providerId:string;upstreamModel:string;litellmModelName:string;litellmModelId?:string;status:string;lastError?:string};
type Alias={alias:string;litellmModelName:string};
type Registry={providers:Provider[];models:Model[];aliases:Alias[]};
type Discovery={id:string};
const aliasNames=['fast','balanced','deep','vision'] as const;
const emptyForm={id:'',name:'',providerType:'vllm' as ProviderType,baseUrl:'',apiKey:'',enabled:true};
const typeHelp:Record<ProviderType,{label:string;hint:string;placeholder:string}>={
  vllm:{label:'vLLM',hint:'OpenAI-compatible /v1 endpoint',placeholder:'http://10.90.0.11:8000'},
  lmstudio:{label:'LM Studio',hint:'Local Server · OpenAI-compatible',placeholder:'http://10.90.0.12:1234'},
  ollama:{label:'Ollama',hint:'Native Ollama API',placeholder:'http://10.90.0.13:11434'},
};
function safeName(value:string){return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,48)}
function modelSlug(value:string){return value.toLowerCase().replace(/[^a-z0-9._-]+/g,'-').replace(/^-|-$/g,'').slice(0,80)}

export function AdminProviders(){
  const [registry,setRegistry]=useState<Registry>({providers:[],models:[],aliases:[]});
  const [form,setForm]=useState(emptyForm);const [busy,setBusy]=useState('');const [message,setMessage]=useState('');const [discoveries,setDiscoveries]=useState<Record<string,Discovery[]>>({});
  const load=useCallback(async()=>{const r=await fetch('/api/admin/model-providers',{cache:'no-store'});if(r.ok)setRegistry(await r.json())},[]);
  useEffect(()=>{const t=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(t)},[load]);
  const activeModels=useMemo(()=>registry.models.filter(m=>m.status==='active'),[registry.models]);
  const saveProvider=async(e:React.FormEvent)=>{e.preventDefault();setBusy('save');setMessage('');try{const path=form.id?`/api/admin/model-providers/${encodeURIComponent(form.id)}`:'/api/admin/model-providers';const r=await fetch(path,{method:form.id?'PUT':'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:form.name,providerType:form.providerType,baseUrl:form.baseUrl,apiKey:form.apiKey,enabled:form.enabled})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to save provider');setMessage(d.test?.status==='ok'?`Connected to ${form.name}. ${d.test.message}`:`Saved, but test failed: ${d.test?.message||'Unknown error'}`);setForm(emptyForm);await load()}catch(e){setMessage(e instanceof Error?e.message:'Unable to save provider')}finally{setBusy('')}};
  const edit=(p:Provider)=>{setForm({id:p.id,name:p.name,providerType:p.providerType,baseUrl:p.baseUrl,apiKey:'',enabled:p.enabled});setMessage(p.hasApiKey?'API key is already stored. Leave it blank to keep the existing key.':'')};
  const test=async(p:Provider)=>{setBusy(`test:${p.id}`);setMessage('');const r=await fetch(`/api/admin/model-providers/${encodeURIComponent(p.id)}/test`,{method:'POST'});const d=await r.json().catch(()=>({}));setMessage(r.ok?`Connected to ${p.name} · ${d.models?.length||0} models · ${d.latencyMs||0}ms`:d.error||'Connection failed');if(r.ok)setDiscoveries(x=>({...x,[p.id]:d.models||[]}));await load();setBusy('')};
  const discover=async(p:Provider)=>{setBusy(`discover:${p.id}`);setMessage('');const r=await fetch(`/api/admin/model-providers/${encodeURIComponent(p.id)}/discover`,{cache:'no-store'});const d=await r.json().catch(()=>({}));if(r.ok){setDiscoveries(x=>({...x,[p.id]:d.models||[]}));setMessage(`Found ${d.models?.length||0} models on ${p.name}.`)}else setMessage(d.error||'Discovery failed');setBusy('')};
  const addModel=async(p:Provider,upstream:string)=>{const litellmModelName=`${safeName(p.name)||p.providerType}-${modelSlug(upstream)}`;setBusy(`model:${p.id}:${upstream}`);setMessage('');const r=await fetch(`/api/admin/model-providers/${encodeURIComponent(p.id)}/models`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({upstreamModel:upstream,litellmModelName})});const d=await r.json().catch(()=>({}));setMessage(r.ok?`${upstream} registered in LiteLLM as ${litellmModelName}.`:d.detail||d.error||'LiteLLM registration failed');await load();setBusy('')};
  const deleteModel=async(m:Model)=>{if(!confirm(`Remove ${m.litellmModelName} from LiteLLM?`))return;setBusy(`delmodel:${m.id}`);const r=await fetch(`/api/admin/provider-models/${encodeURIComponent(m.id)}`,{method:'DELETE'});const d=await r.json().catch(()=>({}));setMessage(r.ok?'Model removed.':d.detail||d.error||'Unable to remove model');await load();setBusy('')};
  const deleteProvider=async(p:Provider)=>{if(!confirm(`Delete provider ${p.name} and its registered models?`))return;setBusy(`del:${p.id}`);const r=await fetch(`/api/admin/model-providers/${encodeURIComponent(p.id)}`,{method:'DELETE'});const d=await r.json().catch(()=>({}));setMessage(r.ok?'Provider removed.':d.detail||d.error||'Unable to remove provider');await load();setBusy('')};
  const setAlias=async(alias:string,model:string)=>{setBusy(`alias:${alias}`);const r=await fetch(`/api/admin/model-aliases/${alias}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({litellmModelName:model})});const d=await r.json().catch(()=>({}));setMessage(r.ok?`${alias} now routes to ${model}.`:d.error||'Unable to update route');await load();setBusy('')};
  return <>
    <header className="pageHeader"><div><div className="eyebrow">Inference</div><h1>Model Providers</h1><p>Connect vLLM, LM Studio or Ollama, register their models in LiteLLM and route Daiki aliases without restarting the gateway.</p></div><button className="btn ghost" onClick={()=>void load()}><RefreshCw size={16}/> Refresh</button></header>
    {message?<div className="notice butter sectionGap"><span>{message}</span></div>:null}
    <div className="providerLayout sectionGap">
      <form className="surface providerForm" onSubmit={saveProvider}>
        <div className="sectionHead"><div><div className="eyebrow">Step 1</div><h2>{form.id?'Edit provider':'Connect provider'}</h2></div><ServerCog size={22}/></div>
        <label><span>Name</span><input className="input" required maxLength={80} value={form.name} onChange={e=>setForm(x=>({...x,name:e.target.value}))} placeholder="Office vLLM"/></label>
        <label><span>Type</span><select className="input" value={form.providerType} onChange={e=>setForm(x=>({...x,providerType:e.target.value as ProviderType}))}>{Object.entries(typeHelp).map(([k,v])=><option key={k} value={k}>{v.label}</option>)}</select><small>{typeHelp[form.providerType].hint}</small></label>
        <label><span>Endpoint</span><input className="input" required type="url" value={form.baseUrl} onChange={e=>setForm(x=>({...x,baseUrl:e.target.value}))} placeholder={typeHelp[form.providerType].placeholder}/></label>
        <label><span>API key <em>optional</em></span><input className="input" type="password" autoComplete="new-password" value={form.apiKey} onChange={e=>setForm(x=>({...x,apiKey:e.target.value}))} placeholder={form.id?'Leave blank to keep existing key':'Leave blank if provider has no auth'}/></label>
        <div className="actions"><button className="btn primary" disabled={!!busy}><Link2 size={16}/>{busy==='save'?'Connecting…':form.id?'Save & test':'Connect & test'}</button>{form.id?<button type="button" className="btn ghost" onClick={()=>setForm(emptyForm)}>Cancel</button>:null}</div>
      </form>
      <section className="surface aliasPanel"><div className="sectionHead"><div><div className="eyebrow">Step 3</div><h2>Daiki routes</h2></div><Zap size={21}/></div><p className="muted small">Aliases update at runtime. Existing environment routes remain fallback until you assign a model here.</p>{aliasNames.map(alias=>{const current=registry.aliases.find(a=>a.alias===alias)?.litellmModelName||'';return <label className="aliasRow" key={alias}><span>{alias}</span><select className="input" value={current} disabled={!activeModels.length||busy===`alias:${alias}`} onChange={e=>void setAlias(alias,e.target.value)}><option value="" disabled>{activeModels.length?'Choose model':'Register a model first'}</option>{activeModels.map(m=><option key={m.id} value={m.litellmModelName}>{m.litellmModelName}</option>)}</select></label>})}</section>
    </div>
    <section className="sectionGap"><div className="sectionHead"><div><div className="eyebrow">Step 2</div><h2>Connected providers</h2></div><span className="muted small">{registry.providers.length} configured</span></div><div className="providerGrid sectionGap">{registry.providers.map(p=>{const models=registry.models.filter(m=>m.providerId===p.id);const discovered=discoveries[p.id]||[];const registered=new Set(models.map(m=>m.upstreamModel));return <article className="surface providerCard" key={p.id}><div className="providerCardHead"><div className={`providerLogo ${p.providerType}`}><Cpu size={20}/></div><div><h3>{p.name}</h3><span>{typeHelp[p.providerType].label} · {p.baseUrl}</span></div><span className={`status ${p.lastTestStatus==='ok'?'status-approved':p.lastTestStatus==='error'?'status-rejected':'status-pending'}`}>{p.lastTestStatus==='ok'?'Connected':p.lastTestStatus==='error'?'Error':'Not tested'}</span></div><p className="muted small providerMessage">{p.lastTestMessage||'Run a connection test to discover available models.'}</p><div className="actions"><button className="btn compact" disabled={!!busy} onClick={()=>void test(p)}><Zap size={14}/> Test</button><button className="btn compact" disabled={!!busy} onClick={()=>void discover(p)}><RefreshCw size={14}/> Discover models</button><button className="btn compact" onClick={()=>edit(p)}>Edit</button><button className="btn compact" disabled={!!busy} onClick={()=>void deleteProvider(p)}><Trash2 size={14}/></button></div>{discovered.length?<div className="discoveryList"><strong>Available models</strong>{discovered.map(m=><div className="modelRow" key={m.id}><span>{m.id}</span>{registered.has(m.id)?<span className="status status-approved">Registered</span>:<button className="btn compact" disabled={!!busy} onClick={()=>void addModel(p,m.id)}><Plus size={13}/> Register</button>}</div>)}</div>:null}{models.length?<div className="registeredModels"><strong>LiteLLM models</strong>{models.map(m=><div className="modelRow" key={m.id}><div><span>{m.litellmModelName}</span><small>{m.upstreamModel}</small></div><span className={`status ${m.status==='active'?'status-approved':m.status==='error'?'status-rejected':'status-pending'}`}>{m.status}</span><button className="btn compact" disabled={!!busy} onClick={()=>void deleteModel(m)}><Trash2 size={13}/></button></div>)}</div>:null}</article>})}{!registry.providers.length?<div className="surface emptyProvider"><ServerCog size={28}/><strong>No model providers yet</strong><span>Connect vLLM, LM Studio or Ollama to get started.</span></div>:null}</div></section>
  </>;
}
