'use client';
import Link from 'next/link';
import {useCallback,useEffect,useMemo,useState} from 'react';
type Device={guestSubject:string;deviceId:string;deviceName?:string;requests:number;inputTokens:number;outputTokens:number;totalTokens:number;lastSeenAt:string;lastUsedAt?:string};
type Activity={requestId:string;modelAlias:string;workload:string;inputTokens:number;outputTokens:number;totalTokens:number;status:string;metadata:Record<string,unknown>;startedAt:string;completedAt?:string};
type Attachment={id:string;deviceId:string;name:string;relativePath:string;source:string;mediaType:string;sizeBytes:number;sha256:string;extractStatus:string;createdAt:string};
type ResetEvent={id:number;actorSubject:string;resetAt:string;note:string};
type Detail={guestSubject:string;selectedDeviceId?:string;devices:Device[];usage:{inputTokens:number;outputTokens:number;totalTokens:number};activity:Activity[];attachments:Attachment[];resets:ResetEvent[];quota?:{mode?:string;remaining?:number|null;resetAt?:string}};
const fmt=(n:number)=>new Intl.NumberFormat().format(n||0);const when=(v?:string)=>v?new Date(v).toLocaleString():'—';const bytes=(n:number)=>n>=1024*1024?`${(n/1024/1024).toFixed(1)} MB`:n>=1024?`${(n/1024).toFixed(1)} KB`:`${n} B`;
const asObj=(v:unknown):Record<string,unknown>=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{};
const asStrings=(v:unknown)=>Array.isArray(v)?v.map(String).filter(Boolean):[];
function activitySummary(x:Activity){const m=asObj(x.metadata);const commands=asObj(m.commands);const research=asObj(m.research);const attachments=Array.isArray(m.attachments)?m.attachments:[];const capability=typeof m.guestCapability==='string'?m.guestCapability:'';const tags:string[]=[];if(capability)tags.push(capability);if(typeof commands.mode==='string'&&commands.mode)tags.push('/'+commands.mode);for(const s of asStrings(commands.skills))tags.push('@'+s);for(const s of asStrings(commands.autoSkills))tags.push('@'+s);if(research.used===true)tags.push('web research');if(attachments.length)tags.push(`${attachments.length} attachment${attachments.length>1?'s':''}`);return tags}
export function AdminGuestDetail({guestSubject}:{guestSubject:string}){
 const [data,setData]=useState<Detail|null>(null);const [device,setDevice]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [loadError,setLoadError]=useState('');
 const load=useCallback(async(deviceId:string)=>{setLoadError('');try{const r=await fetch(`/api/admin/guests/${encodeURIComponent(guestSubject)}${deviceId?`?deviceId=${encodeURIComponent(deviceId)}`:''}`,{cache:'no-store'});const d=await r.json().catch(()=>({})) as Detail&{error?:string};if(!r.ok){setLoadError(d.error||`โหลด Guest detail ไม่สำเร็จ (${r.status})`);return}setData(d)}catch(e){setLoadError(e instanceof Error?e.message:String(e))}},[guestSubject]);
 useEffect(()=>{const t=window.setTimeout(()=>void load(device),0);return()=>window.clearTimeout(t)},[load,device]);
 const stats=useMemo(()=>{const ds=data?.devices||[];return {requests:ds.reduce((n,x)=>n+x.requests,0),tokens:ds.reduce((n,x)=>n+x.totalTokens,0),lastSeen:ds.reduce((v,x)=>!v||new Date(x.lastSeenAt)>new Date(v)?x.lastSeenAt:v,'')}} ,[data]);
 const reset=async()=>{setBusy(true);setMessage('');const r=await fetch(`/api/admin/guests/${encodeURIComponent(guestSubject)}/quota-reset`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({note:'Reset from Guest detail'})});const d=await r.json().catch(()=>({})) as {error?:string};setMessage(r.ok?'Reset quota และ runtime counters แล้ว':d.error||'Reset ไม่สำเร็จ');if(r.ok)await load(device);setBusy(false)};
 if(!data)return <div className="surface"><div className="emptyState">{loadError?<><strong>โหลด Guest detail ไม่สำเร็จ</strong><div className="muted small sectionGap">{loadError}</div><button className="btn sectionGap" onClick={()=>void load(device)}>ลองใหม่</button></>:<>Loading Guest detail…</>}</div></div>;
 return <><header className="pageHeader"><div><div className="eyebrow">Guest intelligence</div><h1>{guestSubject.slice(0,22)}{guestSubject.length>22?'…':''}</h1><p><code>{guestSubject}</code> · raw IP ไม่ถูกเก็บ</p></div><div className="actions"><Link className="btn ghost" href="/admin/guests">Back to guests</Link><button className="btn" disabled={busy} onClick={()=>void reset()}>{busy?'Resetting…':'Reset quota'}</button></div></header>
 <div className="pastelGrid"><div className="pastelCard peach"><span>Devices</span><strong>{data.devices.length}</strong><small>known Guest devices</small></div><div className="pastelCard sky"><span>Requests</span><strong>{fmt(stats.requests)}</strong><small>completed requests</small></div><div className="pastelCard mint"><span>Tokens</span><strong>{fmt(data.usage.totalTokens||stats.tokens)}</strong><small>{fmt(data.usage.inputTokens)} in · {fmt(data.usage.outputTokens)} out</small></div><div className="pastelCard butter"><span>Last seen</span><strong className="guestDateKpi">{when(stats.lastSeen)}</strong><small>{data.quota?.mode||'guest'} quota</small></div></div>
 {message?<div className="notice butter sectionGap">{message}</div>:null}
 <section className="surface sectionGap"><div className="sectionHead"><div><h2>Conversation & activity</h2><p className="muted small">แสดงข้อความที่ Guest ส่ง, คำตอบของ Daiki, mode/skill, model, token และสถานะในแต่ละ turn</p></div><select className="input select" value={device} onChange={e=>setDevice(e.target.value)}><option value="">All devices</option>{data.devices.map(d=><option key={d.deviceId} value={d.deviceId}>{d.deviceName||'Unnamed'} · {d.deviceId.slice(0,12)}</option>)}</select></div>
 <div className="guestTimeline sectionGap">{data.activity.length?data.activity.map(x=>{const m=asObj(x.metadata);const prompt=typeof m.guestPrompt==='string'?m.guestPrompt:'';const answer=typeof m.guestResponse==='string'?m.guestResponse:'';const deviceName=typeof m.guestDeviceName==='string'&&m.guestDeviceName?m.guestDeviceName:String(m.guestDeviceId||'Unknown device');const tags=activitySummary(x);return <article className="guestTurn" key={x.requestId}><div className="guestTurnHead"><div><strong>{deviceName}</strong><span>{when(x.startedAt)} · <code>{x.requestId}</code></span></div><div className="guestTurnMeta"><span className={`status status-${x.status}`}>{x.status}</span><span>{x.modelAlias} · {x.workload}</span><b>{fmt(x.totalTokens)} tokens</b></div></div>{tags.length?<div className="guestTurnTags">{tags.map((t,i)=><span key={`${t}-${i}`}>{t}</span>)}</div>:null}<div className="guestConversationPair"><div className="guestSpeech user"><span>Guest</span><p>{prompt||'ข้อความของ turn นี้ยังไม่ได้ถูก capture (activity เก่าก่อนเปิด Guest history)'}</p></div><div className="guestSpeech assistant"><span>Daiki</span><p>{answer||'ไม่มี response text ที่บันทึกไว้สำหรับ turn นี้'}</p></div></div><details className="guestRaw"><summary>Request details</summary><pre className="metadataPre">{JSON.stringify(m,null,2)}</pre></details></article>}):<div className="emptyState">ยังไม่มี conversation/activity สำหรับ Guest หรือ device นี้</div>}</div></section>
 <section className="adminGrid"><article className="surface"><div className="sectionHead"><div><h2>Devices</h2><p className="muted small">Device identity, last seen และ usage</p></div></div><div className="detailList sectionGap">{data.devices.map(d=><button className={`guestDeviceRow ${device===d.deviceId?'active':''}`} key={d.deviceId} onClick={()=>setDevice(d.deviceId)}><div><strong>{d.deviceName||'Unnamed device'}</strong><code>{d.deviceId}</code></div><span>{fmt(d.requests)} req · {fmt(d.totalTokens)} tokens<br/><small>{when(d.lastSeenAt)}</small></span></button>)}</div></article><article className="surface"><div className="sectionHead"><div><h2>Reset history</h2><p className="muted small">Admin quota/runtime reset events</p></div></div>{data.resets.length?<div className="detailList sectionGap">{data.resets.map(r=><div className="detailListRow" key={r.id}><div><strong>{r.note||'Guest reset'}</strong><div className="muted small">{r.actorSubject}</div></div><span>{when(r.resetAt)}</span></div>)}</div>:<div className="emptyState">No reset history.</div>}</article></section>
 <section className="surface tableSurface sectionGap"><div className="sectionHead"><div><h2>Guest files & generated assets</h2><p className="muted small">Upload, generated file และ generated image ที่ยังเก็บอยู่</p></div><span className="muted small">{data.attachments.length} items</span></div><div className="tableWrap"><table className="table"><thead><tr><th>Time</th><th>Device</th><th>Name</th><th>Action</th><th>Type</th><th>Size</th></tr></thead><tbody>{data.attachments.map(a=><tr key={a.id}><td className="small">{when(a.createdAt)}</td><td><code>{a.deviceId.slice(0,14)}{a.deviceId.length>14?'…':''}</code></td><td><strong>{a.name}</strong><div className="muted small">{a.relativePath}</div></td><td><span className="status">{a.source}</span></td><td className="small">{a.mediaType}</td><td>{bytes(a.sizeBytes)}</td></tr>)}</tbody></table>{!data.attachments.length?<div className="emptyState">No stored Guest files.</div>:null}</div></section></>;
}
