'use client';
import Link from 'next/link';
import {useCallback,useEffect,useMemo,useState} from 'react';

type UserStatus='pending'|'approved'|'suspended'|'rejected';
type User={subject:string;displayName?:string;email?:string;status:UserStatus;authProvider?:string;roles?:string[];lastLoginAt?:string;createdAt?:string;approvedAt?:string};
type Interval='hour'|'day'|'week'|'month'|'rolling'|'custom'|'lifetime';
type Quota={quotaMode:'unlimited'|'limited';tokenLimit?:number;intervalKind:Interval;intervalSeconds?:number};

export function AdminUsers(){
 const [users,setUsers]=useState<User[]>([]);const [filter,setFilter]=useState('all');const [query,setQuery]=useState('');const [busy,setBusy]=useState('');const [message,setMessage]=useState('');
 const [email,setEmail]=useState('');const [displayName,setDisplayName]=useState('');const [newStatus,setNewStatus]=useState<UserStatus>('pending');const [makeAdmin,setMakeAdmin]=useState(false);const [createdSecret,setCreatedSecret]=useState('');
 const [quotaUser,setQuotaUser]=useState<User|null>(null);const [quota,setQuota]=useState<Quota>({quotaMode:'unlimited',intervalKind:'month'});
 const load=useCallback(async()=>{const r=await fetch('/api/admin/users',{cache:'no-store'});if(r.ok)setUsers(await r.json())},[]);useEffect(()=>{const t=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(t)},[load]);
 const shown=useMemo(()=>users.filter(u=>(filter==='all'||u.status===filter)&&(!query||`${u.displayName||''} ${u.email||''} ${u.subject}`.toLowerCase().includes(query.toLowerCase()))),[users,filter,query]);
 const create=async()=>{if(!email.trim())return;setBusy('create');setMessage('');setCreatedSecret('');const roles=makeAdmin?['ai-user','ai-admin']:['ai-user'];const r=await fetch('/api/admin/users',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:email.trim(),displayName:displayName.trim(),status:newStatus,roles})});const d=await r.json().catch(()=>({}));if(r.ok){setCreatedSecret(d.temporaryPassword||'');setMessage('User created in Keycloak and Daiki.');setEmail('');setDisplayName('');await load()}else setMessage(d.error||'User creation failed');setBusy('')};
 const updateStatus=async(u:User,status:UserStatus)=>{setBusy(u.subject);await fetch(`/api/admin/users/${encodeURIComponent(u.subject)}/status`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({status})});await load();setBusy('')};
 const updateRoles=async(u:User,admin:boolean)=>{setBusy(u.subject);const roles=admin?['ai-user','ai-admin']:['ai-user'];const r=await fetch(`/api/admin/users/${encodeURIComponent(u.subject)}/roles`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({roles})});if(r.ok)await load();setBusy('')};
 const openQuota=async(u:User)=>{setQuotaUser(u);const r=await fetch(`/api/admin/users/${encodeURIComponent(u.subject)}/quota`,{cache:'no-store'});if(r.ok){const d=await r.json();setQuota({...{quotaMode:'unlimited',intervalKind:'month'},...(d.policy||{})})}};
 const saveQuota=async()=>{if(!quotaUser)return;setBusy('quota');const payload={...quota,tokenLimit:quota.quotaMode==='limited'?Number(quota.tokenLimit||0):undefined,intervalSeconds:['rolling','custom'].includes(quota.intervalKind)?Number(quota.intervalSeconds||3600):undefined};const r=await fetch(`/api/admin/users/${encodeURIComponent(quotaUser.subject)}/quota`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});setMessage(r.ok?'User quota saved.':'Unable to save user quota.');if(r.ok)setQuotaUser(null);setBusy('')};
 return <><header className="pageHeader"><div><div className="eyebrow">Access Control</div><h1>User Management</h1><p>Create identities, approve access, assign admin roles and override token quotas.</p></div><div className="actions"><input className="input userSearch" placeholder="Search users" value={query} onChange={e=>setQuery(e.target.value)}/><select className="input select" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="suspended">Suspended</option><option value="rejected">Rejected</option></select></div></header>
 <section className="surface"><div className="sectionHead"><div><h2>Create user</h2><p className="muted small">Creates a native Keycloak identity and matching Daiki application account.</p></div></div><div className="formGrid sectionGap"><label><span>Email</span><input className="input" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="user@example.com"/></label><label><span>Display name</span><input className="input" value={displayName} onChange={e=>setDisplayName(e.target.value)} placeholder="Name"/></label><label><span>Initial status</span><select className="input" value={newStatus} onChange={e=>setNewStatus(e.target.value as UserStatus)}><option value="pending">Pending</option><option value="approved">Approved</option></select></label><label className="checkField"><input type="checkbox" checked={makeAdmin} onChange={e=>setMakeAdmin(e.target.checked)}/><span>Grant ai-admin role</span></label></div><div className="actions sectionGap"><button className="btn primary" disabled={busy==='create'||!email.trim()} onClick={()=>void create()}>{busy==='create'?'Creating…':'Create user'}</button></div>{createdSecret?<div className="secretBox sectionGap"><span>Temporary password · copy now</span><code>{createdSecret}</code><button className="btn compact" onClick={()=>navigator.clipboard.writeText(createdSecret)}>Copy</button></div>:null}{message?<div className="notice butter sectionGap">{message}</div>:null}</section>
 <section className="surface tableSurface sectionGap"><div className="sectionHead"><h2>Users</h2><span className="muted small">{shown.length} shown · {users.length} total</span></div><div className="tableWrap"><table className="table"><thead><tr><th>User</th><th>Provider</th><th>Roles</th><th>Status</th><th>Last login</th><th>Actions</th></tr></thead><tbody>{shown.map(u=>{const admin=(u.roles||[]).includes('ai-admin');return <tr key={u.subject}><td><strong>{u.displayName||u.email||'User'}</strong><div className="muted small">{u.email||u.subject}</div></td><td>{u.authProvider||'email'}</td><td>{(u.roles||[]).filter(x=>x.startsWith('ai-')).join(', ')||'—'}</td><td><span className={`status status-${u.status}`}>{u.status}</span></td><td className="small">{u.lastLoginAt?new Date(u.lastLoginAt).toLocaleString():'—'}</td><td><div className="actions">{u.status!=='approved'?<button className="btn compact" disabled={busy===u.subject} onClick={()=>void updateStatus(u,'approved')}>Approve</button>:<button className="btn compact ghost" disabled={busy===u.subject} onClick={()=>void updateStatus(u,'suspended')}>Suspend</button>}{u.status==='pending'?<button className="btn compact ghost" disabled={busy===u.subject} onClick={()=>void updateStatus(u,'rejected')}>Reject</button>:null}<button className="btn compact ghost" disabled={busy===u.subject} onClick={()=>void updateRoles(u,!admin)}>{admin?'Remove admin':'Make admin'}</button><Link className="btn compact" href={`/admin/users/${encodeURIComponent(u.subject)}`}>Details</Link><button className="btn compact ghost" onClick={()=>void openQuota(u)}>Quota</button></div></td></tr>})}</tbody></table>{!shown.length?<div className="emptyState">No users match this view.</div>:null}</div></section>
 {quotaUser?<div className="modalBackdrop" onMouseDown={()=>setQuotaUser(null)}><div className="modalCard" onMouseDown={e=>e.stopPropagation()}><div className="sectionHead"><div><div className="eyebrow">User override</div><h2>{quotaUser.displayName||quotaUser.email}</h2></div><button className="btn compact ghost" onClick={()=>setQuotaUser(null)}>Close</button></div><div className="formGrid sectionGap"><label><span>Mode</span><select className="input" value={quota.quotaMode} onChange={e=>setQuota(x=>({...x,quotaMode:e.target.value as Quota['quotaMode']}))}><option value="unlimited">Unlimited</option><option value="limited">Limited</option></select></label><label><span>Window</span><select className="input" value={quota.intervalKind} onChange={e=>setQuota(x=>({...x,intervalKind:e.target.value as Interval}))}>{['hour','day','week','month','rolling','custom','lifetime'].map(x=><option key={x}>{x}</option>)}</select></label>{quota.quotaMode==='limited'?<label><span>Token limit</span><input className="input" type="number" min="0" value={quota.tokenLimit??100000} onChange={e=>setQuota(x=>({...x,tokenLimit:Number(e.target.value)}))}/></label>:null}{['rolling','custom'].includes(quota.intervalKind)?<label><span>Seconds</span><input className="input" type="number" min="1" value={quota.intervalSeconds??3600} onChange={e=>setQuota(x=>({...x,intervalSeconds:Number(e.target.value)}))}/></label>:null}</div><div className="actions sectionGap"><button className="btn primary" disabled={busy==='quota'} onClick={()=>void saveQuota()}>Save quota</button></div></div></div>:null}</>;
}
