'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {QuotaPolicyFields,defaultQuotaPolicy,quotaPolicyPayload,type QuotaPolicy} from './QuotaPolicyFields';
type WindowKind='hour'|'day'|'week'|'month'|'rolling'|'custom'|'lifetime';
type UsageRow={subject:string;email?:string;displayName?:string;status:string;totalTokens:number;requests:number};
type GuestPolicy={enabled:boolean;tokenLimit:number;intervalKind:WindowKind;intervalSeconds?:number;requestsPerHour:number;minIntervalSeconds:number;maxCompletionTokens:number;fastModel:string};
type GuestUsage={inputTokens:number;outputTokens:number;totalTokens:number};
const DEFAULT_GUEST:GuestPolicy={enabled:true,tokenLimit:4000,intervalKind:'day',requestsPerHour:6,minIntervalSeconds:45,maxCompletionTokens:384,fastModel:'fast'};
const windows:WindowKind[]=['hour','day','week','month','rolling','custom','lifetime'];
export function AdminTokens(){
  const [policy,setPolicy]=useState<QuotaPolicy>(defaultQuotaPolicy);const [rows,setRows]=useState<UsageRow[]>([]);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
  const [guest,setGuest]=useState<GuestPolicy>(DEFAULT_GUEST);const [guestUsage,setGuestUsage]=useState<GuestUsage>({inputTokens:0,outputTokens:0,totalTokens:0});const [guestRequests,setGuestRequests]=useState(0);const [guestBusy,setGuestBusy]=useState(false);const [guestMessage,setGuestMessage]=useState('');
  const load=useCallback(async()=>{const [p,u,g]=await Promise.all([fetch('/api/admin/token-policy',{cache:'no-store'}),fetch('/api/admin/usage',{cache:'no-store'}),fetch('/api/admin/guest-policy',{cache:'no-store'})]);if(p.ok){const d=await p.json();const next=d.policy||{};setPolicy({...defaultQuotaPolicy,...next,parallelLimits:Array.isArray(next.parallelLimits)?next.parallelLimits:[]})}if(u.ok)setRows(await u.json());if(g.ok){const d=await g.json();setGuest({...DEFAULT_GUEST,...(d.policy||{})});setGuestUsage({inputTokens:Number(d.usage?.inputTokens||0),outputTokens:Number(d.usage?.outputTokens||0),totalTokens:Number(d.usage?.totalTokens||0)});setGuestRequests(Number(d.requests||0))}},[]);
  useEffect(()=>{const t=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(t)},[load]);
  const total=useMemo(()=>rows.reduce((n,r)=>n+(r.totalTokens||0),0),[rows]);
  const save=async()=>{setBusy(true);setMessage('');const payload={...quotaPolicyPayload(policy),allowedModels:['auto','fast','balanced','deep']};const r=await fetch('/api/admin/token-policy',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));setMessage(r.ok?'System token policy saved.':d.error||'Unable to save policy');if(r.ok)await load();setBusy(false)};
  const saveGuest=async()=>{setGuestBusy(true);setGuestMessage('');const payload={...guest,tokenLimit:Number(guest.tokenLimit||0),requestsPerHour:Number(guest.requestsPerHour||1),minIntervalSeconds:Number(guest.minIntervalSeconds||0),maxCompletionTokens:Number(guest.maxCompletionTokens||1),intervalSeconds:['rolling','custom'].includes(guest.intervalKind)?Number(guest.intervalSeconds||3600):undefined,fastModel:'fast'};const r=await fetch('/api/admin/guest-policy',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));setGuestMessage(r.ok?'Guest access policy saved.':d.error||'Unable to save guest policy');if(r.ok)await load();setGuestBusy(false)};
  return <><header className="pageHeader"><div><div className="eyebrow">Entitlements</div><h1>Token Settings</h1><p>Control authenticated quotas and the stricter public Guest access policy from one place.</p></div><button className="btn primary" disabled={busy} onClick={()=>void save()}>{busy?'Saving…':'Save user policy'}</button></header>
  <div className="pastelGrid"><div className="pastelCard peach"><span>System mode</span><strong>{policy.quotaMode}</strong><small>authenticated default</small></div><div className="pastelCard sky"><span>Guest access</span><strong>{guest.enabled?'On':'Off'}</strong><small>Fast only</small></div><div className="pastelCard mint"><span>User usage</span><strong>{new Intl.NumberFormat().format(total)}</strong><small>completed tokens</small></div><div className="pastelCard butter"><span>Guest usage</span><strong>{new Intl.NumberFormat().format(guestUsage.totalTokens)}</strong><small>{new Intl.NumberFormat().format(guestRequests)} requests</small></div></div>
  <section className="surface sectionGap"><div className="sectionHead"><div><h2>Authenticated default policy</h2><p className="muted small">User/API-key overrides take precedence over this system default. Parallel quota windows remain supported.</p></div></div><QuotaPolicyFields policy={policy} onChange={setPolicy}/>{message?<div className="notice butter sectionGap">{message}</div>:null}</section>
  <section className="surface sectionGap guestPolicyCard"><div className="sectionHead"><div><div className="eyebrow">Public access</div><h2>Guest Chat</h2><p className="muted small">Guest users are always restricted to Fast text chat. History, files, web research, tools and other model routes stay login-only.</p></div><label className="guestSwitch"><input type="checkbox" checked={guest.enabled} onChange={e=>setGuest(x=>({...x,enabled:e.target.checked}))}/><span>{guest.enabled?'Enabled':'Disabled'}</span></label></div><div className="formGrid guestPolicyGrid sectionGap"><label><span>Token quota</span><input className="input" type="number" min="0" value={guest.tokenLimit} onChange={e=>setGuest(x=>({...x,tokenLimit:Number(e.target.value)}))}/><small>Per anonymous network identity and quota window.</small></label><label><span>Quota window</span><select className="input" value={guest.intervalKind} onChange={e=>setGuest(x=>({...x,intervalKind:e.target.value as WindowKind}))}>{windows.map(x=><option key={x}>{x}</option>)}</select><small>When Guest token quota resets.</small></label>{['rolling','custom'].includes(guest.intervalKind)?<label><span>Window seconds</span><input className="input" type="number" min="1" value={guest.intervalSeconds??3600} onChange={e=>setGuest(x=>({...x,intervalSeconds:Number(e.target.value)}))}/><small>Required for rolling/custom windows.</small></label>:null}<label><span>Requests / hour</span><input className="input" type="number" min="1" max="10000" value={guest.requestsPerHour} onChange={e=>setGuest(x=>({...x,requestsPerHour:Number(e.target.value)}))}/><small>Hard hourly ceiling per Guest network identity.</small></label><label><span>Minimum gap (sec)</span><input className="input" type="number" min="0" max="3600" value={guest.minIntervalSeconds} onChange={e=>setGuest(x=>({...x,minIntervalSeconds:Number(e.target.value)}))}/><small>Cooldown between messages.</small></label><label><span>Max output tokens</span><input className="input" type="number" min="1" max="8192" value={guest.maxCompletionTokens} onChange={e=>setGuest(x=>({...x,maxCompletionTokens:Number(e.target.value)}))}/><small>Per-response output ceiling.</small></label><label><span>Allowed route</span><input className="input" value="Fast" disabled/><small>Guest cannot select Auto, Balanced or Deep.</small></label></div><div className="guestPolicyFooter"><div><strong>{new Intl.NumberFormat().format(guestUsage.totalTokens)}</strong><span> tokens · </span><strong>{new Intl.NumberFormat().format(guestRequests)}</strong><span> requests</span></div><button className="btn primary" disabled={guestBusy} onClick={()=>void saveGuest()}>{guestBusy?'Saving…':'Save Guest policy'}</button></div>{guestMessage?<div className="notice butter sectionGap">{guestMessage}</div>:null}</section>
  <section className="surface tableSurface sectionGap"><div className="sectionHead"><h2>Authenticated usage overview</h2><span className="muted small">Per-user overrides remain configurable from Users</span></div><div className="tableWrap"><table className="table"><thead><tr><th>User</th><th>Status</th><th>Requests</th><th>Total tokens</th></tr></thead><tbody>{rows.map(r=><tr key={r.subject}><td><strong>{r.displayName||r.email||r.subject}</strong><div className="muted small">{r.email||r.subject}</div></td><td><span className={`status status-${r.status}`}>{r.status}</span></td><td>{r.requests}</td><td><strong>{new Intl.NumberFormat().format(r.totalTokens||0)}</strong></td></tr>)}</tbody></table></div></section></>;
}
