'use client';
import {useCallback,useEffect,useState} from 'react';

type User={subject:string;email?:string;displayName?:string;status:string};
type Key={id:string;ownerSubject:string;name:string;keyPrefix:string;scopes:string[];status:string;createdAt:string;expiresAt?:string;lastUsedAt?:string};
type Interval='hour'|'day'|'week'|'month'|'rolling'|'custom'|'lifetime';
type Policy={quotaMode:'unlimited'|'limited';tokenLimit?:number;intervalKind:Interval;intervalSeconds?:number};
const defaultPolicy:Policy={quotaMode:'unlimited',intervalKind:'month'};

export function AdminKeys(){
 const [keys,setKeys]=useState<Key[]>([]);const [users,setUsers]=useState<User[]>([]);const [name,setName]=useState('developer-key');const [owner,setOwner]=useState('');const [expiry,setExpiry]=useState('');const [secret,setSecret]=useState('');const [busy,setBusy]=useState('');const [message,setMessage]=useState('');const [quotaKey,setQuotaKey]=useState<Key|null>(null);const [policy,setPolicy]=useState<Policy>(defaultPolicy);
 const load=useCallback(async()=>{const [k,u]=await Promise.all([fetch('/api/admin/keys',{cache:'no-store'}),fetch('/api/admin/users',{cache:'no-store'})]);if(k.ok)setKeys(await k.json());if(u.ok){const list=await u.json() as User[];setUsers(list);setOwner(x=>x||list.find(v=>v.status==='approved')?.subject||list[0]?.subject||'')}},[]);
 useEffect(()=>{const t=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(t)},[load]);
 const create=async()=>{if(!owner||!name.trim())return;setBusy('create');setSecret('');setMessage('');const body={name:name.trim(),ownerSubject:owner,scopes:['inference'],expiresAt:expiry?new Date(expiry).toISOString():undefined};const r=await fetch('/api/admin/keys',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(r.ok){setSecret(d.key||'');setMessage('API key created. Copy the secret now; it will not be shown again.');await load()}else setMessage(d.error||'API key creation failed');setBusy('')};
 const revoke=async(k:Key)=>{if(!confirm(`Revoke ${k.name}?`))return;setBusy(k.id);const r=await fetch(`/api/admin/keys/${encodeURIComponent(k.id)}`,{method:'DELETE'});if(r.ok)await load();setBusy('')};
 const openQuota=async(k:Key)=>{setQuotaKey(k);const r=await fetch(`/api/admin/keys/${encodeURIComponent(k.id)}/quota`,{cache:'no-store'});if(r.ok){const d=await r.json();setPolicy({...defaultPolicy,...(d.policy||{})})}else setPolicy(defaultPolicy)};
 const saveQuota=async()=>{if(!quotaKey)return;setBusy(quotaKey.id);const payload={...policy,tokenLimit:policy.quotaMode==='limited'?Number(policy.tokenLimit||0):undefined,intervalSeconds:['rolling','custom'].includes(policy.intervalKind)?Number(policy.intervalSeconds||3600):undefined};const r=await fetch(`/api/admin/keys/${encodeURIComponent(quotaKey.id)}/quota`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});setMessage(r.ok?'API key quota saved.':'Unable to save API key quota.');if(r.ok)setQuotaKey(null);setBusy('')};
 const ownerName=(id:string)=>{const u=users.find(x=>x.subject===id);return u?.displayName||u?.email||id};
 return <><header className="pageHeader"><div><div className="eyebrow">Developer access</div><h1>API Keys</h1><p>Generate Daiki-owned credentials with an explicit owner, inference scope, expiry and independent quota.</p></div></header>
 <section className="surface"><div className="sectionHead"><div><h2>Generate key</h2><p className="muted small">Plaintext secret is returned once. Only a hash and short prefix are stored.</p></div></div><div className="formGrid sectionGap"><label><span>Name</span><input className="input" value={name} onChange={e=>setName(e.target.value)}/></label><label><span>Owner</span><select className="input" value={owner} onChange={e=>setOwner(e.target.value)}>{users.filter(u=>u.status==='approved').map(u=><option key={u.subject} value={u.subject}>{u.displayName||u.email||u.subject}</option>)}</select></label><label><span>Scope</span><input className="input" value="inference" disabled/></label><label><span>Expires at</span><input className="input" type="datetime-local" value={expiry} onChange={e=>setExpiry(e.target.value)}/></label></div><div className="actions sectionGap"><button className="btn primary" disabled={busy==='create'||!owner} onClick={()=>void create()}>{busy==='create'?'Generating…':'Generate API key'}</button></div>{secret?<div className="secretBox sectionGap"><span>Copy now</span><code>{secret}</code><button className="btn compact" onClick={()=>navigator.clipboard.writeText(secret)}>Copy</button></div>:null}{message?<div className="notice butter sectionGap">{message}</div>:null}</section>
 <section className="surface tableSurface sectionGap"><div className="sectionHead"><h2>Keys</h2><span className="muted small">{keys.filter(k=>k.status==='active').length} active</span></div><div className="tableWrap"><table className="table"><thead><tr><th>Name</th><th>Owner</th><th>Scope</th><th>Expiry</th><th>Last used</th><th>Status</th><th>Actions</th></tr></thead><tbody>{keys.map(k=><tr key={k.id}><td><strong>{k.name}</strong><div className="muted small">{k.keyPrefix}…</div></td><td>{ownerName(k.ownerSubject)}</td><td>{k.scopes.join(', ')}</td><td>{k.expiresAt?new Date(k.expiresAt).toLocaleString():'Never'}</td><td>{k.lastUsedAt?new Date(k.lastUsedAt).toLocaleString():'—'}</td><td><span className={`status status-${k.status}`}>{k.status}</span></td><td><div className="actions"><button className="btn compact ghost" disabled={busy===k.id||k.status!=='active'} onClick={()=>void openQuota(k)}>Quota</button><button className="btn compact ghost" disabled={busy===k.id||k.status!=='active'} onClick={()=>void revoke(k)}>Revoke</button></div></td></tr>)}</tbody></table>{!keys.length?<div className="emptyState">No API keys yet.</div>:null}</div></section>
 {quotaKey?<div className="modalBackdrop" onMouseDown={()=>setQuotaKey(null)}><div className="modalCard" onMouseDown={e=>e.stopPropagation()}><div className="sectionHead"><div><div className="eyebrow">API key override</div><h2>{quotaKey.name}</h2></div><button className="btn compact ghost" onClick={()=>setQuotaKey(null)}>Close</button></div><div className="formGrid sectionGap"><label><span>Mode</span><select className="input" value={policy.quotaMode} onChange={e=>setPolicy(x=>({...x,quotaMode:e.target.value as Policy['quotaMode']}))}><option value="unlimited">Unlimited</option><option value="limited">Limited</option></select></label><label><span>Window</span><select className="input" value={policy.intervalKind} onChange={e=>setPolicy(x=>({...x,intervalKind:e.target.value as Interval}))}>{['hour','day','week','month','rolling','custom','lifetime'].map(x=><option key={x}>{x}</option>)}</select></label>{policy.quotaMode==='limited'?<label><span>Token limit</span><input className="input" type="number" min="0" value={policy.tokenLimit??100000} onChange={e=>setPolicy(x=>({...x,tokenLimit:Number(e.target.value)}))}/></label>:null}{['rolling','custom'].includes(policy.intervalKind)?<label><span>Seconds</span><input className="input" type="number" min="1" value={policy.intervalSeconds??3600} onChange={e=>setPolicy(x=>({...x,intervalSeconds:Number(e.target.value)}))}/></label>:null}</div><div className="actions sectionGap"><button className="btn primary" disabled={busy===quotaKey.id} onClick={()=>void saveQuota()}>Save quota</button></div></div></div>:null}</>;
}
