'use client';
import Link from 'next/link';
import {useCallback,useEffect,useState} from 'react';

type WindowKind='hour'|'day'|'week'|'month'|'rolling'|'custom'|'lifetime';
type GuestPolicy={
  enabled:boolean;quotaMode:'limited'|'unlimited';tokenLimit:number;intervalKind:WindowKind;intervalSeconds?:number;requestsPerHour:number;minIntervalSeconds:number;maxCompletionTokens:number;fastModel:string;
  allowUploads:boolean;allowImageGeneration:boolean;allowFileGeneration:boolean;maxUploadBytes:number;maxImageUploadBytes:number;maxUploadsPerHour:number;maxStoredFiles:number;maxStoredBytes:number;maxAttachmentsPerMessage:number;attachmentRetentionHours:number;
  imageGenerationsPerDay:number;fileGenerationsPerDay:number;maxGeneratedFileBytes:number;maxGeneratedImageBytes:number;
};
type GuestDevice={guestSubject:string;deviceId:string;deviceName?:string;requests:number;totalTokens:number;lastSeenAt:string};
type GuestPolicyPayload={policy?:Partial<GuestPolicy>;usage?:{totalTokens?:number};requests?:number;devices?:GuestDevice[]};
const MiB=1024*1024;
const DEFAULT_GUEST:GuestPolicy={enabled:true,quotaMode:'limited',tokenLimit:4000,intervalKind:'day',requestsPerHour:6,minIntervalSeconds:45,maxCompletionTokens:384,fastModel:'fast',allowUploads:true,allowImageGeneration:true,allowFileGeneration:true,maxUploadBytes:10*MiB,maxImageUploadBytes:4*MiB,maxUploadsPerHour:10,maxStoredFiles:20,maxStoredBytes:50*MiB,maxAttachmentsPerMessage:10,attachmentRetentionHours:24,imageGenerationsPerDay:3,fileGenerationsPerDay:5,maxGeneratedFileBytes:MiB,maxGeneratedImageBytes:4*MiB};
const windows:WindowKind[]=['hour','day','week','month','rolling','custom','lifetime'];
const fmt=(n:number)=>new Intl.NumberFormat().format(n||0);
const fmtBytes=(n:number)=>n===0?'Unlimited':n>=1024*1024*1024?`${(n/1024/1024/1024).toFixed(1)} GB`:n>=1024*1024?`${(n/1024/1024).toFixed(1)} MB`:n>=1024?`${(n/1024).toFixed(1)} KB`:`${n} B`;
function LimitField({label,value,onChange,max,unit='count',detail}:{label:string;value:number;onChange:(n:number)=>void;max:number;unit?:'count'|'mib';detail?:string}){
  const limited=value>0;const shown=unit==='mib'?(limited?value/MiB:1):(limited?value:1);
  return <label className="resourceLimitField"><span>{label}</span><div className="resourceLimitControl"><select className="input" value={limited?'limited':'unlimited'} onChange={e=>onChange(e.target.value==='unlimited'?0:(unit==='mib'?MiB:1))}><option value="unlimited">Unlimited</option><option value="limited">Limited</option></select>{limited?<input className="input" type="number" min={unit==='mib'?0.1:1} step={unit==='mib'?0.1:1} max={unit==='mib'?max/MiB:max} value={shown} onChange={e=>{const n=Math.max(unit==='mib'?0.1:1,Number(e.target.value)||0);onChange(unit==='mib'?Math.round(n*MiB):Math.round(n))}}/>:null}{limited&&unit==='mib'?<small>MiB</small>:null}</div>{detail?<small>{detail}</small>:null}</label>;
}
export function AdminGuestPolicy(){
  const [guest,setGuest]=useState<GuestPolicy>(DEFAULT_GUEST);const [tokens,setTokens]=useState(0);const [requests,setRequests]=useState(0);const [devices,setDevices]=useState<GuestDevice[]>([]);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
  const load=useCallback(async()=>{const r=await fetch('/api/admin/guest-policy',{cache:'no-store'});if(!r.ok)return;const d=await r.json() as GuestPolicyPayload;setGuest({...DEFAULT_GUEST,...(d.policy||{})});setTokens(Number(d.usage?.totalTokens||0));setRequests(Number(d.requests||0));setDevices(Array.isArray(d.devices)?d.devices:[])},[]);
  useEffect(()=>{const t=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(t)},[load]);
  const save=async()=>{setBusy(true);setMessage('');const payload={...guest,tokenLimit:Math.max(0,Number(guest.tokenLimit||0)),requestsPerHour:Math.max(0,Number(guest.requestsPerHour||0)),minIntervalSeconds:Math.max(0,Number(guest.minIntervalSeconds||0)),maxCompletionTokens:Math.max(1,Number(guest.maxCompletionTokens||1)),maxUploadBytes:Math.max(0,Number(guest.maxUploadBytes||0)),maxImageUploadBytes:Math.max(0,Number(guest.maxImageUploadBytes||0)),maxUploadsPerHour:Math.max(0,Number(guest.maxUploadsPerHour||0)),maxStoredFiles:Math.max(0,Number(guest.maxStoredFiles||0)),maxStoredBytes:Math.max(0,Number(guest.maxStoredBytes||0)),maxAttachmentsPerMessage:Math.max(0,Number(guest.maxAttachmentsPerMessage||0)),attachmentRetentionHours:Math.max(1,Number(guest.attachmentRetentionHours||1)),imageGenerationsPerDay:Math.max(0,Number(guest.imageGenerationsPerDay||0)),fileGenerationsPerDay:Math.max(0,Number(guest.fileGenerationsPerDay||0)),maxGeneratedFileBytes:Math.max(0,Number(guest.maxGeneratedFileBytes||0)),maxGeneratedImageBytes:Math.max(0,Number(guest.maxGeneratedImageBytes||0)),intervalSeconds:['rolling','custom'].includes(guest.intervalKind)?Math.max(1,Number(guest.intervalSeconds||3600)):undefined,fastModel:'fast'};const r=await fetch('/api/admin/guest-policy',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({})) as {error?:string};setMessage(r.ok?'บันทึก Guest policy แล้ว และมีผลกับ request ใหม่ทันที':d.error||'ไม่สามารถบันทึก Guest policy ได้');if(r.ok)await load();setBusy(false)};
  const networkCount=new Set(devices.map(x=>x.guestSubject)).size;
  return <section className="surface sectionGap guestPolicyCard compactGuestPolicy">
    <div className="sectionHead"><div><div className="eyebrow">Public access</div><h2>Guest Access</h2><p className="muted small">ตั้งค่า Guest แบบย่อ ส่วนรายละเอียดเปิดดูเมื่อจำเป็น และแยกการตรวจสอบ Guest ไปที่หน้า Guest Management</p></div><div className="actions"><Link className="btn ghost" href="/admin/guests">Manage guests</Link><label className="guestSwitch"><input type="checkbox" checked={guest.enabled} onChange={e=>setGuest(x=>({...x,enabled:e.target.checked}))}/><span>{guest.enabled?'Enabled':'Disabled'}</span></label></div></div>
    <div className="guestPolicySummary sectionGap"><div><span>Status</span><strong>{guest.enabled?'On':'Off'}</strong><small>Hermes · Fast / Vision on demand</small></div><div><span>Quota</span><strong>{guest.quotaMode==='unlimited'?'Unlimited':fmt(guest.tokenLimit)}</strong><small>{guest.intervalKind} · {guest.requestsPerHour===0?'∞':guest.requestsPerHour}/hour</small></div><div><span>Guest activity</span><strong>{fmt(networkCount)} networks</strong><small>{fmt(devices.length)} devices · {fmt(requests)} requests</small></div><div><span>Usage</span><strong>{fmt(tokens)}</strong><small>completed tokens</small></div></div>
    <details className="guestPolicyDetails sectionGap"><summary><span><strong>Chat & token limits</strong><small>{guest.minIntervalSeconds}s gap · max {fmt(guest.maxCompletionTokens)} output tokens</small></span><b>Configure</b></summary><div className="formGrid guestPolicyGrid guestPolicyDetailsBody">
      <label><span>Token quota</span><select className="input" value={guest.quotaMode} onChange={e=>setGuest(x=>({...x,quotaMode:e.target.value as GuestPolicy['quotaMode']}))}><option value="unlimited">Unlimited</option><option value="limited">Limited</option></select></label>
      {guest.quotaMode==='limited'?<label><span>Token limit</span><input className="input" type="number" min="0" value={guest.tokenLimit} onChange={e=>setGuest(x=>({...x,tokenLimit:Number(e.target.value)}))}/><small>Per hashed Guest network.</small></label>:null}
      {guest.quotaMode==='limited'?<label><span>Quota window</span><select className="input" value={guest.intervalKind} onChange={e=>setGuest(x=>({...x,intervalKind:e.target.value as WindowKind}))}>{windows.map(x=><option key={x}>{x}</option>)}</select></label>:null}
      {guest.quotaMode==='limited'&&['rolling','custom'].includes(guest.intervalKind)?<label><span>Window seconds</span><input className="input" type="number" min="1" value={guest.intervalSeconds??3600} onChange={e=>setGuest(x=>({...x,intervalSeconds:Number(e.target.value)}))}/></label>:null}
      <LimitField label="Chat requests / hour" value={guest.requestsPerHour} max={10000} onChange={v=>setGuest(x=>({...x,requestsPerHour:v}))}/><label><span>Minimum gap (sec)</span><input className="input" type="number" min="0" max="3600" value={guest.minIntervalSeconds} onChange={e=>setGuest(x=>({...x,minIntervalSeconds:Number(e.target.value)}))}/><small>0 = off.</small></label><label><span>Max output tokens</span><input className="input" type="number" min="1" max="8192" value={guest.maxCompletionTokens} onChange={e=>setGuest(x=>({...x,maxCompletionTokens:Number(e.target.value)}))}/></label>
    </div></details>
    <details className="guestPolicyDetails sectionGap"><summary><span><strong>Files, images & generation</strong><small>Upload {fmtBytes(guest.maxUploadBytes)} · Image {fmtBytes(guest.maxImageUploadBytes)} · retention {guest.attachmentRetentionHours}h</small></span><b>Configure</b></summary><div className="formGrid guestPolicyGrid resourceQuotaGrid guestPolicyDetailsBody">
      <label className="guestSwitch"><input type="checkbox" checked={guest.allowUploads} onChange={e=>setGuest(x=>({...x,allowUploads:e.target.checked}))}/><span>Uploads {guest.allowUploads?'On':'Off'}</span></label><label className="guestSwitch"><input type="checkbox" checked={guest.allowImageGeneration} onChange={e=>setGuest(x=>({...x,allowImageGeneration:e.target.checked}))}/><span>Image generation {guest.allowImageGeneration?'On':'Off'}</span></label><label className="guestSwitch"><input type="checkbox" checked={guest.allowFileGeneration} onChange={e=>setGuest(x=>({...x,allowFileGeneration:e.target.checked}))}/><span>File generation {guest.allowFileGeneration?'On':'Off'}</span></label>
      <LimitField label="Uploads / hour" value={guest.maxUploadsPerHour} max={1000} onChange={v=>setGuest(x=>({...x,maxUploadsPerHour:v}))}/><LimitField label="Stored files / network" value={guest.maxStoredFiles} max={1000} onChange={v=>setGuest(x=>({...x,maxStoredFiles:v}))}/><LimitField label="Stored size / network" value={guest.maxStoredBytes} unit="mib" max={2048*MiB} onChange={v=>setGuest(x=>({...x,maxStoredBytes:v}))}/><LimitField label="Attachments / message" value={guest.maxAttachmentsPerMessage} max={10} onChange={v=>setGuest(x=>({...x,maxAttachmentsPerMessage:v}))}/><LimitField label="Max uploaded file" value={guest.maxUploadBytes} unit="mib" max={25*MiB} onChange={v=>setGuest(x=>({...x,maxUploadBytes:v}))}/><LimitField label="Max uploaded image" value={guest.maxImageUploadBytes} unit="mib" max={4*MiB} onChange={v=>setGuest(x=>({...x,maxImageUploadBytes:v}))}/><LimitField label="Image generations / day" value={guest.imageGenerationsPerDay} max={1000} onChange={v=>setGuest(x=>({...x,imageGenerationsPerDay:v}))}/><LimitField label="File generations / day" value={guest.fileGenerationsPerDay} max={1000} onChange={v=>setGuest(x=>({...x,fileGenerationsPerDay:v}))}/><LimitField label="Max generated file" value={guest.maxGeneratedFileBytes} unit="mib" max={25*MiB} onChange={v=>setGuest(x=>({...x,maxGeneratedFileBytes:v}))}/><LimitField label="Max generated image" value={guest.maxGeneratedImageBytes} unit="mib" max={4*MiB} onChange={v=>setGuest(x=>({...x,maxGeneratedImageBytes:v}))}/><label><span>Attachment retention (hours)</span><input className="input" type="number" min="1" max={720} value={guest.attachmentRetentionHours} onChange={e=>setGuest(x=>({...x,attachmentRetentionHours:Number(e.target.value)}))}/></label>
    </div></details>
    <div className="guestPolicyFooter"><span className="muted small">Guest history และ conversation ดูได้จาก Guest Management</span><button className="btn primary" disabled={busy} onClick={()=>void save()}>{busy?'Saving…':'Save Guest policy'}</button></div>{message?<div className="notice butter sectionGap">{message}</div>:null}
  </section>;
}
