'use client';
import {useCallback,useEffect,useState} from 'react';

type UserStatus='pending'|'approved'|'suspended'|'rejected';
type User={subject:string;displayName?:string;email?:string;status:UserStatus;authProvider?:string;lastLoginAt?:string};
type Interval='hour'|'day'|'week'|'month'|'lifetime';

export function AdminUsers(){
  const [users,setUsers]=useState<User[]>([]);const [busy,setBusy]=useState('');const [filter,setFilter]=useState('all');
  const load=useCallback(async()=>{const r=await fetch('/api/admin/users',{cache:'no-store'});if(r.ok)setUsers(await r.json())},[]);
  useEffect(()=>{const t=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(t)},[load]);
  const updateStatus=async(u:User,status:UserStatus)=>{setBusy(u.subject);await fetch(`/api/admin/users/${encodeURIComponent(u.subject)}/status`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({status})});await load();setBusy('')};
  const quota=async(u:User)=>{const mode=(prompt(`Quota for ${u.email||u.displayName}: unlimited or limited`,'limited')||'').trim();if(!['unlimited','limited'].includes(mode))return;let tokenLimit:number|undefined;let intervalKind:Interval='month';if(mode==='limited'){tokenLimit=Number(prompt('Token limit','1000000'));if(!Number.isFinite(tokenLimit)||tokenLimit<0)return;intervalKind=(prompt('Interval: hour, day, week, month, lifetime','month')||'month') as Interval;if(!['hour','day','week','month','lifetime'].includes(intervalKind))return}setBusy(u.subject);await fetch(`/api/admin/users/${encodeURIComponent(u.subject)}/quota`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({quotaMode:mode,tokenLimit,intervalKind})});setBusy('')};
  const shown=filter==='all'?users:users.filter(x=>x.status===filter);
  return <><header className="pageHeader"><div><div className="eyebrow">Access</div><h1>Users</h1><p>Approve members and set a plan that fits how they use Daiki.</p></div><select className="input select" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All users</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="suspended">Suspended</option><option value="rejected">Rejected</option></select></header><section className="surface tableSurface"><div className="tableWrap"><table className="table"><thead><tr><th>User</th><th>Provider</th><th>Status</th><th>Last login</th><th>Actions</th></tr></thead><tbody>{shown.map(u=><tr key={u.subject}><td><strong>{u.displayName||u.email||'User'}</strong><div className="muted small">{u.email||u.subject}</div></td><td>{u.authProvider||'keycloak'}</td><td><span className={`status status-${u.status}`}>{u.status}</span></td><td className="small">{u.lastLoginAt?new Date(u.lastLoginAt).toLocaleString():'—'}</td><td><div className="actions">{u.status!=='approved'?<button className="btn compact" disabled={busy===u.subject} onClick={()=>void updateStatus(u,'approved')}>Approve</button>:<button className="btn compact" disabled={busy===u.subject} onClick={()=>void updateStatus(u,'suspended')}>Suspend</button>}{u.status==='pending'?<button className="btn compact ghost" disabled={busy===u.subject} onClick={()=>void updateStatus(u,'rejected')}>Reject</button>:null}<button className="btn compact ghost" disabled={busy===u.subject} onClick={()=>void quota(u)}>Quota</button></div></td></tr>)}</tbody></table>{!shown.length?<div className="emptyState">No users in this filter.</div>:null}</div></section></>;
}
