'use client';
import Link from 'next/link';
import {useState} from 'react';
import {ArrowLeft,Mail} from 'lucide-react';

export default function ForgotPassword(){
  const [email,setEmail]=useState('');const [busy,setBusy]=useState(false);const [sent,setSent]=useState(false);
  const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!email.trim()||busy)return;setBusy(true);try{await fetch('/api/auth/password-reset',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:email.trim()})});setSent(true)}finally{setBusy(false)}};
  return <main className="loginPage"><section className="loginLayout"><div className="loginStory"><Link className="loginBrand" href="/"><span>Daiki<span>●</span></span><small>AI Passport</small></Link><div className="storyCopy"><div className="eyebrow">Password help</div><h1>We’ll help you<br/>get back in.</h1><p>Enter the email you use with Daiki. If there is an account, we’ll send a secure link to choose a new password.</p><div className="storyTags"><span className="tag peach">15 min link</span><span className="tag sky">Private</span><span className="tag mint">Secure</span></div></div><div className="storyFooter"><Mail size={16}/> Reset links are sent by Daiki AI Passport.</div></div><div className="loginPanel">{sent?<><div><div className="eyebrow">Check your inbox</div><h2>Reset link sent</h2><p className="muted">If an account exists for <strong>{email}</strong>, you’ll receive an email with a link to set a new password. The link expires in 15 minutes.</p></div><Link href="/login" className="btn primary loginBtn"><ArrowLeft size={16}/> Back to sign in</Link></>:<><div><div className="eyebrow">Forgot password</div><h2>Reset your password</h2><p className="muted">We’ll email a secure reset link. For privacy, the response is the same even if an account does not exist.</p></div><form className="authForm" onSubmit={submit}><label className="muted small" htmlFor="reset-email">Email address</label><input id="reset-email" className="input" type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/><button className="btn primary loginBtn" disabled={busy}>{busy?'Sending…':'Send reset link'}</button></form><Link href="/login" className="btn ghost loginBtn"><ArrowLeft size={16}/> Back to sign in</Link></>}</div></section></main>
}
