'use client';
import {useEffect,useState} from 'react';

type Prefs={defaultModel:string;responseStyle:string;researchMode:'auto'|'web'|'off'};
const DEFAULT:Prefs={defaultModel:'auto',responseStyle:'balanced',researchMode:'auto'};
export default function Settings(){
  const [prefs,setPrefs]=useState(DEFAULT);const [saved,setSaved]=useState(false);
  useEffect(()=>{const t=window.setTimeout(()=>{try{setPrefs({...DEFAULT,...JSON.parse(localStorage.getItem('daiki_preferences')||'{}')})}catch{}},0);return()=>window.clearTimeout(t)},[]);
  const save=()=>{localStorage.setItem('daiki_preferences',JSON.stringify(prefs));setSaved(true);setTimeout(()=>setSaved(false),1600)};
  return <><header className="pageHeader"><div><div className="eyebrow">Preferences</div><h1>Settings</h1><p>Set the defaults Daiki uses when you start a new conversation.</p></div></header><section className="settingsSurface surface"><div className="settingRow"><div><strong>Default model route</strong><p>Auto is recommended. Daiki can pick the best configured route for the task.</p></div><select className="input" value={prefs.defaultModel} onChange={e=>setPrefs(x=>({...x,defaultModel:e.target.value}))}><option value="auto">Auto</option><option value="fast">Fast</option><option value="balanced">Balanced</option><option value="deep">Deep</option></select></div><div className="settingRow"><div><strong>Web research</strong><p>Auto searches when information may be current. On searches every message. Off never searches.</p></div><select className="input" value={prefs.researchMode} onChange={e=>setPrefs(x=>({...x,researchMode:e.target.value as Prefs['researchMode']}))}><option value="auto">Auto</option><option value="web">Always on</option><option value="off">Off</option></select></div><div className="settingRow"><div><strong>Response style</strong><p>How much detail you usually want in Daiki&apos;s answers.</p></div><select className="input" value={prefs.responseStyle} onChange={e=>setPrefs(x=>({...x,responseStyle:e.target.value}))}><option value="concise">Concise</option><option value="balanced">Balanced</option><option value="detailed">Detailed</option></select></div><div className="settingsFooter"><button className="btn primary" onClick={save}>{saved?'Saved ✓':'Save preferences'}</button></div></section></>}
